/**
 * Font Awesome solo trae términos en inglés. Cada palabra del slug suma sus
 * equivalentes en español, con y sin acento (la búsqueda es `ILIKE`). Solo el
 * slug: los términos secundarios son demasiado amplios («home» está en Baseball).
 */
const ES_BY_TOKEN: Record<string, readonly string[]> = {
	home: ['inicio', 'casa', 'hogar'],
	house: ['casa', 'hogar', 'inicio'],
	user: ['usuario', 'persona', 'perfil'],
	users: ['usuarios', 'personas', 'grupo'],
	person: ['persona', 'usuario'],
	people: ['personas', 'gente'],
	group: ['grupo', 'equipo'],
	team: ['equipo', 'grupo'],
	employee: ['empleado', 'personal', 'trabajador'],
	profile: ['perfil'],
	account: ['cuenta'],
	avatar: ['perfil', 'usuario'],
	gear: ['configuración', 'ajustes', 'engrane'],
	gears: ['configuración', 'ajustes', 'engranes'],
	cog: ['configuración', 'ajustes', 'engrane'],
	settings: ['configuración', 'ajustes'],
	sliders: ['ajustes', 'controles'],
	wrench: ['herramienta', 'llave', 'reparar', 'mantenimiento'],
	screwdriver: ['desarmador', 'herramienta'],
	toolbox: ['herramientas', 'caja de herramientas'],
	hammer: ['martillo', 'herramienta'],
	tool: ['herramienta'],
	tools: ['herramientas'],
	repair: ['reparar', 'reparación'],
	search: ['buscar', 'búsqueda', 'lupa'],
	magnifying: ['buscar', 'lupa'],
	filter: ['filtro', 'filtrar'],
	list: ['lista', 'listado'],
	checklist: ['lista de verificación', 'pendientes'],
	task: ['tarea', 'pendiente'],
	tasks: ['tareas', 'pendientes'],
	table: ['tabla'],
	grid: ['cuadrícula', 'rejilla'],
	bars: ['menú', 'barras'],
	dashboard: ['tablero', 'panel', 'indicadores'],
	gauge: ['tablero', 'indicador', 'velocímetro'],
	chart: ['gráfica', 'gráfico', 'estadísticas', 'reporte'],
	graph: ['gráfica', 'gráfico'],
	pie: ['pastel', 'gráfica de pastel'],
	statistics: ['estadísticas'],
	analytics: ['análisis', 'estadísticas'],
	report: ['reporte', 'informe'],
	calendar: ['calendario', 'fecha', 'agenda'],
	date: ['fecha'],
	schedule: ['horario', 'agenda', 'programar'],
	appointment: ['cita'],
	clock: ['reloj', 'hora'],
	time: ['tiempo', 'hora'],
	timer: ['temporizador', 'cronómetro'],
	stopwatch: ['cronómetro'],
	hourglass: ['reloj de arena', 'espera'],
	history: ['historial'],
	bell: ['campana', 'notificación', 'aviso'],
	notification: ['notificación', 'aviso'],
	alert: ['alerta', 'aviso'],
	warning: ['advertencia', 'alerta', 'precaución'],
	exclamation: ['exclamación', 'alerta'],
	info: ['información'],
	information: ['información'],
	question: ['pregunta', 'duda', 'ayuda'],
	help: ['ayuda', 'soporte'],
	support: ['soporte', 'ayuda'],
	check: ['palomita', 'revisar', 'correcto', 'aprobar'],
	xmark: ['cerrar', 'cancelar', 'tache'],
	close: ['cerrar'],
	cancel: ['cancelar'],
	plus: ['agregar', 'más', 'nuevo'],
	add: ['agregar', 'nuevo'],
	minus: ['menos', 'quitar'],
	trash: ['basura', 'eliminar', 'borrar', 'papelera'],
	delete: ['eliminar', 'borrar'],
	remove: ['quitar', 'eliminar'],
	pen: ['pluma', 'editar', 'escribir'],
	pencil: ['lápiz', 'editar', 'escribir'],
	edit: ['editar'],
	eraser: ['borrador'],
	copy: ['copiar'],
	paste: ['pegar'],
	clipboard: ['portapapeles', 'tablilla'],
	save: ['guardar'],
	floppy: ['guardar', 'disquete'],
	download: ['descargar'],
	upload: ['subir', 'cargar'],
	share: ['compartir'],
	link: ['enlace', 'vínculo', 'liga'],
	lock: ['candado', 'bloquear', 'seguridad'],
	padlock: ['candado'],
	unlock: ['desbloquear', 'abrir'],
	key: ['llave', 'clave', 'contraseña'],
	shield: ['escudo', 'seguridad', 'protección'],
	security: ['seguridad'],
	eye: ['ojo', 'ver', 'visible'],
	star: ['estrella', 'favorito'],
	heart: ['corazón', 'favorito', 'me gusta'],
	thumbs: ['pulgar', 'me gusta'],
	flag: ['bandera'],
	tag: ['etiqueta'],
	tags: ['etiquetas'],
	bookmark: ['marcador'],
	thumbtack: ['chincheta', 'pin', 'fijar'],
	pin: ['pin', 'fijar', 'ubicación'],
	map: ['mapa'],
	location: ['ubicación', 'lugar', 'dirección'],
	marker: ['marcador', 'ubicación'],
	route: ['ruta', 'recorrido'],
	road: ['camino', 'carretera', 'calle'],
	compass: ['brújula'],
	globe: ['mundo', 'internet', 'global'],
	earth: ['mundo', 'tierra', 'planeta'],
	language: ['idioma', 'lenguaje'],
	phone: ['teléfono', 'llamada'],
	mobile: ['celular', 'móvil'],
	envelope: ['correo', 'sobre', 'email'],
	mail: ['correo', 'email'],
	email: ['correo'],
	message: ['mensaje'],
	comment: ['comentario', 'mensaje'],
	comments: ['comentarios', 'conversación'],
	chat: ['chat', 'conversación', 'mensaje'],
	inbox: ['bandeja de entrada', 'buzón'],
	send: ['enviar'],
	print: ['imprimir', 'impresora'],
	printer: ['impresora'],
	file: ['archivo', 'documento'],
	document: ['documento'],
	folder: ['carpeta'],
	book: ['libro', 'manual'],
	newspaper: ['periódico', 'noticias'],
	image: ['imagen', 'foto'],
	photo: ['foto', 'fotografía'],
	picture: ['imagen', 'foto'],
	camera: ['cámara', 'foto'],
	video: ['video', 'película'],
	film: ['película'],
	music: ['música'],
	microphone: ['micrófono'],
	headphones: ['audífonos'],
	headset: ['diadema', 'soporte'],
	volume: ['volumen', 'sonido'],
	sound: ['sonido'],
	play: ['reproducir'],
	pause: ['pausa'],
	stop: ['detener', 'alto'],
	power: ['encender', 'apagar', 'energía'],
	plug: ['enchufe', 'conectar'],
	battery: ['batería', 'pila'],
	lightbulb: ['foco', 'idea', 'luz'],
	bolt: ['rayo', 'energía', 'electricidad'],
	sun: ['sol', 'día'],
	moon: ['luna', 'noche'],
	cloud: ['nube'],
	rain: ['lluvia'],
	umbrella: ['paraguas', 'sombrilla'],
	snowflake: ['nieve', 'copo'],
	fire: ['fuego', 'incendio', 'llama'],
	flame: ['llama', 'fuego'],
	water: ['agua'],
	droplet: ['gota', 'agua'],
	faucet: ['llave de agua', 'grifo', 'agua'],
	leaf: ['hoja', 'planta'],
	tree: ['árbol'],
	seedling: ['planta', 'semilla'],
	recycle: ['reciclar'],
	building: ['edificio', 'empresa', 'oficina'],
	city: ['ciudad'],
	store: ['tienda', 'comercio'],
	shop: ['tienda', 'comercio'],
	warehouse: ['almacén', 'bodega', 'inventario'],
	box: ['caja', 'paquete'],
	boxes: ['cajas', 'inventario', 'almacén'],
	package: ['paquete'],
	dolly: ['carretilla', 'almacén'],
	pallet: ['tarima'],
	truck: ['camión', 'envío', 'transporte', 'reparto'],
	shipping: ['envío', 'paquetería'],
	delivery: ['entrega', 'reparto'],
	car: ['auto', 'coche', 'carro', 'vehículo'],
	vehicle: ['vehículo'],
	bus: ['autobús', 'camión'],
	motorcycle: ['moto', 'motocicleta'],
	bicycle: ['bicicleta'],
	plane: ['avión'],
	airplane: ['avión'],
	ship: ['barco'],
	train: ['tren'],
	gas: ['gasolina', 'gas'],
	cart: ['carrito', 'compras'],
	shopping: ['compras', 'comprar'],
	bag: ['bolsa'],
	basket: ['canasta', 'cesta'],
	receipt: ['recibo', 'ticket', 'comprobante'],
	invoice: ['factura'],
	ticket: ['boleto', 'ticket'],
	money: ['dinero'],
	cash: ['efectivo', 'dinero', 'caja'],
	bill: ['billete', 'cuenta'],
	coins: ['monedas'],
	coin: ['moneda'],
	dollar: ['dólar', 'dinero', 'peso'],
	currency: ['moneda', 'dinero'],
	wallet: ['cartera', 'billetera'],
	credit: ['crédito', 'tarjeta'],
	card: ['tarjeta'],
	bank: ['banco'],
	landmark: ['banco', 'gobierno', 'monumento'],
	calculator: ['calculadora'],
	percent: ['porcentaje', 'descuento'],
	payment: ['pago', 'cobro'],
	price: ['precio'],
	hand: ['mano'],
	handshake: ['acuerdo', 'trato', 'saludo'],
	briefcase: ['maletín', 'trabajo', 'portafolio'],
	suitcase: ['maleta', 'viaje'],
	school: ['escuela'],
	graduation: ['graduación', 'estudiante', 'alumno'],
	chalkboard: ['pizarrón', 'clase'],
	teacher: ['maestro', 'profesor'],
	student: ['estudiante', 'alumno'],
	hospital: ['hospital'],
	stethoscope: ['estetoscopio', 'médico'],
	doctor: ['médico', 'doctor'],
	medical: ['médico', 'salud'],
	kit: ['botiquín'],
	ambulance: ['ambulancia', 'emergencia'],
	syringe: ['jeringa', 'vacuna'],
	pills: ['pastillas', 'medicina'],
	capsules: ['cápsulas', 'medicina'],
	prescription: ['receta', 'medicina'],
	tooth: ['diente', 'dentista'],
	dog: ['perro', 'mascota'],
	cat: ['gato', 'mascota'],
	paw: ['huella', 'mascota', 'animal'],
	animal: ['animal'],
	fish: ['pez', 'pescado'],
	horse: ['caballo'],
	utensils: ['cubiertos', 'comida', 'restaurante'],
	food: ['comida', 'alimento'],
	mug: ['taza', 'café'],
	coffee: ['café'],
	cake: ['pastel'],
	gift: ['regalo'],
	trophy: ['trofeo', 'premio'],
	award: ['premio', 'reconocimiento'],
	medal: ['medalla'],
	crown: ['corona'],
	gavel: ['mazo', 'juzgado', 'ley'],
	scale: ['balanza', 'justicia'],
	balance: ['balanza', 'equilibrio'],
	legal: ['legal', 'ley'],
	handcuffs: ['esposas', 'policía'],
	sitemap: ['organigrama', 'jerarquía', 'estructura'],
	diagram: ['diagrama'],
	project: ['proyecto'],
	network: ['red'],
	wifi: ['wifi', 'internet'],
	server: ['servidor'],
	database: ['base de datos'],
	code: ['código', 'programación'],
	terminal: ['terminal', 'consola'],
	bug: ['error', 'bicho'],
	robot: ['robot'],
	qrcode: ['código qr'],
	barcode: ['código de barras'],
	fingerprint: ['huella digital'],
	arrow: ['flecha'],
	up: ['arriba', 'subir'],
	down: ['abajo', 'bajar'],
	left: ['izquierda'],
	right: ['derecha'],
	rotate: ['girar', 'actualizar'],
	refresh: ['actualizar', 'recargar'],
	sync: ['sincronizar', 'actualizar'],
	expand: ['expandir', 'ampliar'],
	compress: ['contraer', 'reducir'],
	sort: ['ordenar'],
	desktop: ['computadora', 'escritorio'],
	computer: ['computadora'],
	laptop: ['laptop', 'portátil'],
	keyboard: ['teclado'],
	mouse: ['ratón'],
	tablet: ['tableta'],
	tv: ['televisión'],
	signal: ['señal'],
	satellite: ['satélite'],
	rocket: ['cohete', 'lanzamiento'],
	industry: ['industria', 'fábrica'],
	factory: ['fábrica'],
	tractor: ['tractor', 'campo'],
	broom: ['escoba', 'limpieza'],
	soap: ['jabón', 'limpieza'],
	shirt: ['camisa', 'ropa'],
	couch: ['sillón', 'sala'],
	bed: ['cama', 'hotel'],
	door: ['puerta'],
	stairs: ['escaleras'],
	parking: ['estacionamiento'],
	traffic: ['tráfico', 'semáforo'],
	sign: ['señal', 'letrero'],
	toilet: ['baño', 'sanitario'],
	restroom: ['baño', 'sanitario'],
	wheelchair: ['silla de ruedas', 'accesibilidad'],
	baby: ['bebé'],
	child: ['niño', 'niña'],
	walking: ['caminar', 'peatón'],
	running: ['correr'],
	futbol: ['fútbol', 'balón'],
	soccer: ['fútbol'],
	basketball: ['básquetbol', 'baloncesto'],
	dumbbell: ['pesas', 'gimnasio'],
	church: ['iglesia', 'templo'],
	skull: ['calavera'],
	face: ['cara', 'carita'],
	smile: ['sonrisa', 'feliz'],
	frown: ['triste'],
	angry: ['enojado'],
	align: ['alinear'],
	bold: ['negrita'],
	italic: ['cursiva'],
	underline: ['subrayado'],
	font: ['fuente', 'letra'],
	paragraph: ['párrafo'],
	quote: ['cita'],
	palette: ['paleta', 'colores'],
	paint: ['pintura', 'pintar'],
	brush: ['pincel', 'brocha'],
	ruler: ['regla', 'medir'],
	crop: ['recortar'],
	scissors: ['tijeras', 'cortar'],
	magnet: ['imán'],
	flask: ['matraz', 'laboratorio', 'química'],
	vial: ['frasco', 'laboratorio'],
	atom: ['átomo', 'ciencia'],
	microscope: ['microscopio'],
	dna: ['adn'],
	bone: ['hueso'],
	brain: ['cerebro'],
	lungs: ['pulmones'],
	virus: ['virus'],
	mask: ['cubrebocas', 'máscara'],
	login: ['entrar', 'iniciar sesión'],
	logout: ['salir', 'cerrar sesión'],
	id: ['credencial', 'identificación'],
	badge: ['gafete', 'insignia'],
	address: ['dirección', 'directorio'],
	contact: ['contacto'],
	ring: ['anillo'],
	helmet: ['casco'],
	construction: ['construcción', 'obra'],
	digging: ['excavar', 'obra'],
	extinguisher: ['extintor'],
	dumpster: ['contenedor', 'basura'],
	bullhorn: ['megáfono', 'anuncio', 'aviso'],
	bullseye: ['objetivo', 'meta', 'diana'],
	puzzle: ['rompecabezas'],
	cube: ['cubo', 'bloque'],
	cubes: ['cubos', 'bloques'],
	layer: ['capa', 'capas'],
	contract: ['contrato'],
	signature: ['firma'],
	stamp: ['sello'],
	certificate: ['certificado'],
	passport: ['pasaporte'],
	vote: ['votar', 'voto'],
	monument: ['monumento'],
	mountain: ['montaña'],
	tent: ['tienda de campaña', 'campamento'],
	hotel: ['hotel'],
	pizza: ['pizza'],
	burger: ['hamburguesa'],
	wine: ['vino', 'bebida'],
	beer: ['cerveza', 'bebida'],
	shower: ['regadera', 'ducha'],
	bath: ['tina', 'baño'],
	emergency: ['emergencia'],
	police: ['policía'],
	education: ['educación'],
	health: ['salud'],
	healthcare: ['salud'],
	transport: ['transporte'],
	transportation: ['transporte'],
	logistics: ['logística'],
	order: ['pedido', 'orden'],
	purchase: ['compra'],
	buy: ['comprar'],
	sale: ['venta'],
	discount: ['descuento'],
	stock: ['existencias', 'inventario'],
	inventory: ['inventario'],
	shelter: ['refugio', 'albergue'],
	weather: ['clima'],
	temperature: ['temperatura'],
	thermometer: ['termómetro'],
};

const plain = (text: string) =>
	text.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

export function icon_search_terms_es(slug: string): string[] {
	const out = new Set<string>();
	for (const token of String(slug ?? '').toLowerCase().split(/[^a-z0-9]+/)) {
		for (const es of ES_BY_TOKEN[token] ?? []) {
			out.add(es);
			out.add(plain(es));
		}
	}
	return [...out];
}
