/**
 * Proyección de listados = `campos_para_proyectar` / tipo del `__read` original.
 * El schema SQL de los súbditos sube campos anidados a columnas; sin esto
 * la lista Angular muestra partidas, widgets y eventos como columnas.
 */
import { type ImperiumDoc } from './envelope.ts';

const RESOURCE_ALIASES: Record<string, string> = {
	proyectos: 'planeacion-proyectos',
	'mis-tareas': 'planeacion-mis-tareas',
	'proyectos-task': 'planeacion-proyectos-task',
	'pedidos-surtir': 'pedidos',
	usuario: 'user',
};

type ListProjection = {
	rows: readonly string[];
	tipo?: readonly string[];
};

const LIST_PROJECTIONS: Record<string, ListProjection> = {
	products: {
		rows: [
			'_id',
			'name',
			'description',
			'existencia',
			'existenciaApartada',
			'existenciaDisponible',
			'costoVenta',
			'costoCompraPromedio',
			'ultimoCostoCompra',
			'fechaUltimaCompra',
			'stockMaximo',
			'stockMinimo',
			'codigo',
			'positional_code',
			'unidad',
			'puedoVenderlo',
			'puedoComprarlo',
			'image',
			'codigos_proveedor',
			'clave_prod_serv',
			'objeto_imp_default',
			'ubicacion_preferida',
			'ubicacion_preferida_codigo',
		],
	},
	'purchase-order': {
		rows: [
			'_id',
			'folio_interno',
			'name',
			'description',
			'proveedor_nombre',
			'proveedor_id',
			'estado',
			'tipo_origen',
			'total_cantidad',
			'total_recibido',
			'subtotal',
			'fecha_aprobacion',
			'fecha_confirmacion',
			'is_active',
		],
	},
	branchoffice: {
		rows: ['_id', 'name', 'location', 'image', 'description', 'is_active'],
	},
	employee: {
		rows: [
			'_id',
			'name',
			'description',
			'puesto',
			'department',
			'branch_office',
			'num_empleado',
			'rfc',
			'curp',
			'is_active',
		],
	},
	reports: {
		rows: [
			'_id',
			'name',
			'description',
			'page_size',
			'pdf_setting',
			'related_model',
			'html_content',
			'generated_report_name',
			'excel_format',
			'excel_sheet_name',
			'is_active',
			'_ref',
		],
		tipo: [
			'name',
			'description',
			'page_size',
			'pdf_setting',
			'related_model',
			'generated_report_name',
			'is_active',
		],
	},
	'delivery-package': {
		rows: [
			'_id',
			'name',
			'codigo_bulto',
			'numero_bulto',
			'pedido_folio',
			'pedido_folio_interno',
			'pedido_contacto_nombre',
			'delivery_route_nombre',
			'vehicle_nombre',
			'peso_kg',
			'contenido_resumen',
			'pedido_total_bultos',
			'estado',
			'is_active',
		],
	},
	'delivery-route': {
		rows: ['_id', 'name', 'description', 'vehicle_name', 'is_active'],
	},
	'pos-session': {
		rows: [
			'_id',
			'consecutivo',
			'diferencia_de_ultimo_cierre',
			'razon_de_diferencia_con_ultimo_cierre',
			'name',
			'description',
			'is_active',
			'status',
			'opening_date',
			'closing_date',
			'cash_register_opening_money',
			'on_use',
			'usage_history',
			'created_by',
			'cashier',
			'branch_office',
		],
	},
	'citizen-report': {
		rows: [
			'_id',
			'name',
			'is_active',
			'citizen_name',
			'citizen_phone',
			'citizen_street',
			'building_number_external',
			'building_number_internal',
			'neighborhood',
			'borough',
			'report_description',
			'citizen_report_problem',
			'employee_taken_the_report',
			'assinged_to',
			'priority',
			'status',
			'department',
			'cuadrilla',
			'jefe_de_cuadrilla',
			'reporting_medium',
			'createdAt',
		],
	},
	asociaciones: {
		rows: ['_id', 'name', 'telefono', 'correo', 'ciudad', 'localidad', 'is_active'],
	},
	'registro-incidencias': {
		rows: [
			'_id',
			'name',
			'alumno_id',
			'grupo_id',
			'registro_asistencia_id',
			'lista_asistencia_id',
			'materia_id',
			'grado_escolar_id',
			'escuela_id',
			'tipo',
			'justificada',
			'evidencia',
			'fecha_asistencia',
			'is_active',
		],
	},
	'medical-file': {
		rows: [
			'_id',
			'paciente_id',
			'numero_expediente',
			'nombre_paciente',
			'fecha_consulta',
			'hora_consulta',
			'status',
			'is_active',
		],
	},
	'ticketing-system-turn': {
		rows: [
			'_id',
			'name',
			'description',
			'movements',
			'customer_type',
			'assigned_box',
			'services',
			'status',
			'time',
			'createdAt',
		],
	},
	'planeacion-proyectos': {
		rows: [
			'_id',
			'name',
			'description',
			'priority',
			'start_date',
			'due_date',
			'owner_user',
			'is_active',
		],
	},
	'planeacion-mis-tareas': {
		rows: [
			'_id',
			'name',
			'description',
			'state',
			'priority',
			'due_date',
			'parent_task',
			'owner_user',
			'is_active',
		],
	},
	'planeacion-proyectos-task': {
		rows: [
			'_id',
			'name',
			'description',
			'status',
			'priority',
			'due_date',
			'project_id',
			'parent_task_id',
			'is_active',
		],
	},
	payments: {
		rows: ['_id', 'name', 'is_active', 'service_slug', 'amount', 'status', 'description'],
	},
	'invoice-request': {
		rows: [
			'_id',
			'name',
			'pedido_folio',
			'contacto_nombre',
			'estado',
			'monto_total',
			'monto_umbral',
			'autorizado_cobranza',
			'requiere_facturacion_dividida',
			'cfdi_document_id',
			'cfdi_document_status',
			'cfdi_document_name',
		],
	},
	'cfdi-document': {
		rows: [
			'_id',
			'name',
			'is_active',
			'status',
			'perfil_emision',
			'flow_direction',
			'receptor_rfc',
			'receptor_nombre',
			'emisor_rfc',
			'emisor_nombre',
			'total',
			'uuid',
			'purchase_order_nombre',
			'purchase_order_id',
		],
	},
	'dynamic-dashboard': {
		rows: ['_id', 'name', 'description', 'is_global', 'is_active'],
	},
	vehicle: {
		rows: [
			'_id',
			'name',
			'placas',
			'numero_economico',
			'marca',
			'modelo',
			'tipo_unidad',
			'estado_operativo',
			'chofer',
			'chofer_nombre',
			'capacidad_carga_kg',
			'anio',
			'is_active',
			'foto',
		],
	},
	'physical-device': {
		rows: [
			'_id',
			'name',
			'hostname',
			'model',
			'serial',
			'os_platform',
			'last_user_name',
			'last_seen',
			'is_active',
		],
	},
	'view-config-preset': {
		rows: ['_id', 'name', 'description', 'scope', 'is_template', 'force_locked', 'is_active'],
	},
	'pos-tickets': {
		rows: [
			'_id',
			'ticket_sequence',
			'ticket_type',
			'pos_session',
			'createdAt',
			'updatedAt',
			'subtotal',
			'total_paid',
			'change',
			'client_id',
			'client_name',
			'client_lastname',
			'client_home',
			'state',
			'is_active',
		],
	},
	'inventory-reception': {
		rows: [
			'_id',
			'name',
			'is_active',
			'estado',
			'purchase_order_nombre',
			'purchase_order_id',
			'producto_id',
			'proveedor_nombre',
			'referencia',
			'fecha_esperada',
			'total_esperado',
			'total_recibido',
		],
	},
	pedidos: {
		rows: [
			'_id',
			'folio_interno',
			'fecha',
			'name',
			'description',
			'estado',
			'contacto',
			'contacto_id',
			'ruta',
			'total',
			'iva',
			'importe',
			'folio',
			'invoice_request_id',
			'invoice_request_name',
			'invoice_request_estado',
			'invoice_request_monto_total',
			'invoice_request_actualizado',
			'assigned_employee',
			'init_time',
			'end_time',
		],
		tipo: [
			'_id',
			'folio_interno',
			'fecha',
			'name',
			'description',
			'estado',
			'contacto',
			'ruta',
			'total',
			'iva',
			'importe',
			'folio',
			'invoice_request_id',
			'invoice_request_name',
			'invoice_request_estado',
			'invoice_request_monto_total',
			'invoice_request_actualizado',
			'assigned_employee',
			'init_time',
			'end_time',
		],
	},
	contacto: {
		rows: [
			'_id',
			'name',
			'is_active',
			'listaDePrecios',
			'esProveedor',
			'rfc',
			'nombre_fiscal',
			'regimen_fiscal',
			'uso_cfdi_default',
			'codigoPostal',
			'codigo',
			'calle',
			'numeroExterior',
			'numeroInterior',
			'colonia',
			'ciudad',
			'estado',
		],
	},
	'payroll-receipt': {
		rows: [
			'_id',
			'name',
			'is_active',
			'payroll_period',
			'employee',
			'estado',
			'neto',
			'total_percepciones',
			'total_deducciones',
			'num_dias_pagados',
		],
	},
	'lista-de-precios': {
		rows: ['_id', 'name', 'is_active'],
	},
	'delivery-return': {
		rows: [
			'_id',
			'name',
			'description',
			'pedido_folio',
			'contacto_nombre',
			'estado',
			'fecha',
			'is_active',
		],
	},
	'inventory-stock-quant': {
		rows: [
			'_id',
			'name',
			'description',
			'producto_nombre',
			'producto_codigo',
			'ubicacion_codigo',
			'cantidad',
			'cantidad_apartada',
			'cantidad_disponible',
			'producto_id',
			'ubicacion_id',
			'is_active',
		],
	},
	'inventory-physical-count': {
		rows: [
			'_id',
			'name',
			'description',
			'ubicacion_codigo',
			'estado',
			'fecha',
			'contado_por',
			'is_active',
			'updatedAt',
			'total_lineas',
		],
	},
	'inventory-movement': {
		rows: [
			'_id',
			'name',
			'description',
			'producto_nombre',
			'producto_codigo',
			'tipo_movimiento',
			'ubicacion_origen_nombre',
			'ubicacion_destino_nombre',
			'documento_tipo',
			'documento_nombre',
			'documento_referencia',
			'producto_id',
			'ubicacion_origen_id',
			'ubicacion_destino_id',
			'cantidad',
			'costo_unitario',
			'stock_total_previo',
			'stock_total_resultante',
			'stock_apartado_previo',
			'stock_apartado_resultante',
			'stock_disponible_resultante',
			'fecha_movimiento',
			'is_active',
		],
	},
	'inventory-cost-entry': {
		rows: [
			'_id',
			'name',
			'receipt_key',
			'recepcion_referencia',
			'orden_compra_nombre',
			'orden_compra_folio',
			'orden_compra_referencia',
			'producto_nombre',
			'producto_codigo',
			'proveedor_nombre',
			'tipo_origen',
			'cantidad',
			'costo_unitario',
			'costo_total',
			'stock_previo',
			'stock_resultante',
			'costo_promedio_resultante',
			'fecha_entrada',
			'is_active',
		],
	},
	'inventory-internal-location': {
		rows: [
			'_id',
			'name',
			'description',
			'codigo',
			'tipo',
			'parent',
			'segmento_codigo',
			'nivel',
			'nivel_nombre',
			'permite_almacenaje',
			'secuencia_surtido',
			'is_system',
			'is_active',
		],
	},
	user: {
		rows: ['_id', 'name', 'is_active', 'img'],
	},
	'pos-order': {
		rows: [
			'_id',
			'partner_name',
			'partner_lastname',
			'partner_home',
			'date_order',
			'amount_total',
			'reference',
		],
	},
	'cfdi-issuer-profile': {
		rows: [
			'_id',
			'name',
			'is_active',
			'rfc',
			'regimen_fiscal',
			'lugar_expedicion',
			'perfil_emision_default',
		],
	},
	'payroll-period': {
		rows: [
			'_id',
			'name',
			'is_active',
			'tipo_nomina',
			'fecha_pago',
			'fecha_inicial',
			'fecha_final',
			'num_dias_pagados',
			'periodicidad_pago',
			'estado',
			'receipts_count',
			'calculated_count',
			'stamped_count',
		],
	},
	'cfdi-catalog': {
		rows: ['_id', 'name', 'is_active', 'catalog', 'code', 'description'],
	},
	'registro-emergencias': {
		rows: [
			'_id',
			'name',
			'fecha_hora_recepcion',
			'tipo_emergencia',
			'prioridad',
			'municipio',
			'resultado',
			'is_active',
		],
	},
	'ticketing-system-box-config': {
		rows: [
			'_id',
			'name',
			'description',
			'box_number',
			'min_movements',
			'max_movements',
			'exclusive',
			'allowed_customer_types',
			'allowed_services',
		],
	},
	'ticketing-system-customer-type': {
		rows: ['_id', 'name', 'description', 'priority_level', 'letter', 'show_to_select'],
	},
	'ticketing-system-service-type': {
		rows: ['_id', 'name', 'is_active', 'priority_level', 'letter', 'show_to_select'],
	},
	'ticketing-system-priority': {
		rows: ['_id', 'name', 'description', 'priority_level'],
	},
	patient: {
		rows: [
			'_id',
			'numero_expediente',
			'nombre_completo',
			'fecha_nacimiento',
			'edad',
			'sexo',
			'estado_civil',
			'ocupacion',
			'telefono_paciente',
			'is_active',
		],
	},
	'labor-incident': {
		rows: [
			'_id',
			'name',
			'description',
			'employee',
			'tipo',
			'fecha_inicio',
			'fecha_fin',
			'dias',
			'horas',
			'importe',
			'tipo_incapacidad',
			'payroll_period',
			'is_active',
		],
	},
	'labor-schedule': {
		rows: ['_id', 'name', 'description', 'employee', 'days', 'is_default', 'is_active'],
	},
	'user-group': {
		rows: ['_id', 'name', 'description'],
	},
	'access-rights': {
		rows: [
			'_id',
			'name',
			'allow_create',
			'allow_read',
			'allow_update',
			'allow_delete',
			'model_id',
		],
	},
	'unit-of-measure': {
		rows: ['_id', 'name', 'is_active', 'clave_unidad', 'description'],
	},
	configuration: {
		rows: [
			'_id',
			'name',
			'description',
			'is_active',
			'is_system',
			'module_id',
			'type',
			'value',
		],
	},
	sku: {
		rows: ['_id', 'name', 'codigo', 'unidad'],
	},
	'menu-management': {
		rows: ['_id', 'name', 'icon', 'model', 'order', 'path', 'parent_id'],
	},
	tags: {
		rows: ['_id', 'name', 'is_active', 'color', 'icon'],
	},
	'interactive-manual': {
		rows: [
			'_id',
			'name',
			'description',
			'is_active',
			'icon',
			'module_model_id',
			'is_default_for_module',
			'steps',
			'assigned_user_ids',
			'assigned_group_ids',
		],
	},
	'module-management': {
		rows: [
			'_id',
			'name',
			'is_enable',
			'model_id',
			'module_name',
			'parent_module',
			'module_location',
		],
	},
	departments: {
		rows: ['_id', 'name', 'is_active'],
	},
	'payroll-concept': {
		rows: [
			'_id',
			'name',
			'description',
			'clave_interna',
			'categoria',
			'tipo_sat',
			'concepto_default',
			'is_system',
			'is_active',
		],
	},
	'lista-asistencia': {
		rows: [
			'_id',
			'name',
			'registro_asistencia_id',
			'alumno_id',
			'grupo_id',
			'alumno_nombre_snapshot',
			'numero_lista',
			'estado',
			'justificada',
			'evidencia',
			'registro_incidencia_id',
			'is_active',
		],
	},
	'record-rules': {
		rows: [
			'_id',
			'name',
			'description',
			'is_active',
			'allow_create',
			'allow_read',
			'allow_update',
			'allow_delete',
			'model_id',
			'group_id',
			'domain',
		],
	},
	'reports-pdf-setting': {
		rows: [
			'_id',
			'name',
			'description',
			'page_size_preset',
			'orientation',
			'custom_width_mm',
			'custom_height_mm',
			'margin_top_mm',
			'margin_right_mm',
			'margin_bottom_mm',
			'margin_left_mm',
			'print_background',
			'prefer_css_page_size',
			'display_header_footer',
			'scale_percent',
			'mirror_margins',
			'is_active',
		],
	},
	'user-print-template': {
		rows: [
			'_id',
			'name',
			'description',
			'source_module',
			'page_size_preset',
			'orientation',
			'updatedAt',
			'is_active',
		],
	},
	violation: {
		rows: ['_id', 'name', 'folio', 'code', 'plates', 'status', 'is_active'],
	},
	'epson-ticket-template': {
		rows: [
			'_id',
			'name',
			'description',
			'is_active',
			'template_key',
			'content',
			'line_width',
			'updatedAt',
		],
	},
	'zpl-management': {
		rows: ['_id', 'name', 'is_active', 'zpl'],
	},
	'attachment-management': {
		rows: [
			'_id',
			'name',
			'description',
			'mimetype',
			'created_by_id',
			'created_by',
			'related_model',
			'related_record_id',
			'size_in_kb',
			'file_ext',
		],
	},
	'user-pin': {
		rows: [
			'_id',
			'name',
			'description',
			'is_active',
			'document_id',
			'document_collection',
			'document_model',
			'document_label',
			'is_global',
			'pin_type',
			'pin_length',
			'auto_generated',
		],
	},
	voluntariado: {
		rows: [
			'_id',
			'name',
			'numero_socio',
			'indicativo',
			'estado',
			'documento_identidad',
			'telefono',
			'correo',
			'localidad',
			'is_active',
		],
	},
	'despensa-solidaria': {
		rows: [
			'_id',
			'name',
			'codigo_barras',
			'categoria',
			'cantidad',
			'stock_minimo',
			'fecha_caducidad',
			'estado',
			'is_active',
		],
	},
	'rescate-animal': {
		rows: [
			'_id',
			'name',
			'nombre_animal',
			'especie',
			'estado',
			'fecha',
			'lugar_encontrado',
			'is_active',
		],
	},
	'inventario-sanitario': {
		rows: [
			'_id',
			'name',
			'categoria',
			'cantidad',
			'stock_minimo',
			'fecha_caducidad',
			'estado',
			'is_active',
		],
	},
	'directorio-contactos': {
		rows: [
			'_id',
			'name',
			'categoria',
			'telefono',
			'telefono_secundario',
			'direccion',
			'web',
			'email',
			'fax',
			'is_active',
		],
	},
	'servicios-realizados': {
		rows: [
			'_id',
			'name',
			'tipo_servicio',
			'fecha_hora_inicio',
			'fecha_hora_fin',
			'total_horas',
			'lugar',
			'is_active',
		],
	},
	cobranza: {
		rows: [
			'_id',
			'name',
			'reference',
			'concept',
			'total_amount',
			'paid_amount',
			'balance',
			'status',
			'is_active',
		],
	},
	'cobranza-payment': {
		rows: ['_id', 'name', 'folio', 'amount', 'status', 'payment_date', 'is_active'],
	},
	'custom-field-control': {
		rows: [
			'_id',
			'name',
			'description',
			'module_name',
			'module_id',
			'model_id',
			'is_active',
			'fields_count',
		],
	},
	alumnos: {
		rows: [
			'_id',
			'name',
			'user_id',
			'grupo_id',
			'numero_lista',
			'email_contacto',
			'telefono_contacto',
			'is_active',
		],
	},
	grupo: {
		rows: ['_id', 'name', 'is_active'],
	},
	materias: {
		rows: ['_id', 'name', 'is_active'],
	},
	escuelas: {
		rows: ['_id', 'name', 'is_active'],
	},
	aulas: {
		rows: ['_id', 'name', 'is_active'],
	},
	horarios: {
		rows: ['_id', 'name', 'is_active'],
	},
	'grados-escolares': {
		rows: ['_id', 'name', 'is_active'],
	},
	'ciclos-escolares': {
		rows: ['_id', 'name', 'is_active'],
	},
	'registro-asistencias': {
		rows: [
			'_id',
			'name',
			'grupo_id',
			'materia_id',
			'teacher_user_id',
			'fecha_asistencia',
			'estatus',
			'total_alumnos',
			'is_active',
		],
	},
};

function projection_for(resource: string): ListProjection | undefined {
	return LIST_PROJECTIONS[resource] ?? LIST_PROJECTIONS[RESOURCE_ALIASES[resource] ?? ''];
}

function instance_map(
	keys: readonly string[],
): Record<string, { nombre_encabezado: string; tipo: string }> {
	const out: Record<string, { nombre_encabezado: string; tipo: string }> = {};
	for (const key of keys) {
		out[key] = { nombre_encabezado: key.replace(/_/g, ' '), tipo: 'string' };
	}
	return out;
}

export function list_instance_type(
	resource: string,
): Record<string, { nombre_encabezado: string; tipo: string }> | null {
	const spec = projection_for(resource);
	if (!spec) return null;
	return instance_map(spec.tipo ?? spec.rows);
}

export function project_list_docs(resource: string, rows: ImperiumDoc[]): ImperiumDoc[] {
	const spec = projection_for(resource);
	if (!spec) return rows;
	const allow = new Set<string>(spec.rows);
	for (const key of spec.rows) allow.add(`${key}_id`);
	return rows.map((row) => {
		const out: ImperiumDoc = {};
		for (const key of allow) {
			if (row[key] !== undefined) out[key] = row[key];
		}
		if (out._id == null && row._id != null) out._id = row._id;
		return out;
	});
}
